//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aufbauwerk.Tools.PdfKit.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aufbauwerk.Tools.PdfKit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The operation is being cancelled... ähnelt.
        /// </summary>
        internal static string Converter_CancelMessage {
            get {
                return ResourceManager.GetString("Converter_CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Converted pages: {0} ähnelt.
        /// </summary>
        internal static string Converter_CompletedPages {
            get {
                return ResourceManager.GetString("Converter_CompletedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following error occured while loading file {0}:
        ///
        ///{1}
        ///
        ///Do you want to ignore the error and proceed with the next file, retry loading the current file or abort the entire operation? ähnelt.
        /// </summary>
        internal static string Converter_ConvertFileError {
            get {
                return ResourceManager.GetString("Converter_ConvertFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} - Convert to {1}... ähnelt.
        /// </summary>
        internal static string Converter_DialogTitle {
            get {
                return ResourceManager.GetString("Converter_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following error occured while loading file {0}:
        ///
        ///{1}
        ///
        ///Do you want to ignore the error and proceed with the next file, retry loading the current file or abort the entire operation? ähnelt.
        /// </summary>
        internal static string Converter_LoadFileError {
            get {
                return ResourceManager.GetString("Converter_LoadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading files... ähnelt.
        /// </summary>
        internal static string Converter_LoadingFiles {
            get {
                return ResourceManager.GetString("Converter_LoadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file format is not supported.
        ///Only the following formats are allowed: {0} ähnelt.
        /// </summary>
        internal static string Document_InvalidFileFormat {
            get {
                return ResourceManager.GetString("Document_InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The page number &apos;{0}&apos; is invalid. ähnelt.
        /// </summary>
        internal static string Document_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Document_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file reports a page count of {0}. ähnelt.
        /// </summary>
        internal static string Document_PageCountOutOfRange {
            get {
                return ResourceManager.GetString("Document_PageCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ghostscript has finished rendering page {0} but not returned a result. ähnelt.
        /// </summary>
        internal static string Document_PageNotRendered {
            get {
                return ResourceManager.GetString("Document_PageNotRendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Ghostscript API call &apos;{0}&apos; returned {1}.
        ///
        ///Output:
        ///{2}
        ///
        ///Error:
        ///{3} ähnelt.
        /// </summary>
        internal static string Ghostscript_Exception {
            get {
                return ResourceManager.GetString("Ghostscript_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No verb has been set. ähnelt.
        /// </summary>
        internal static string Program_NoCommand {
            get {
                return ResourceManager.GetString("Program_NoCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No selected files have been transmitted by Explorer. ähnelt.
        /// </summary>
        internal static string Program_NoFiles {
            get {
                return ResourceManager.GetString("Program_NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The COM server has not been called. ähnelt.
        /// </summary>
        internal static string Program_ServerTimeout {
            get {
                return ResourceManager.GetString("Program_ServerTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsupported verb: {0}
        ///The following verbs are supported: {1}. ähnelt.
        /// </summary>
        internal static string Program_UnknownVerb {
            get {
                return ResourceManager.GetString("Program_UnknownVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die USAGE:
        ///  {0} {1}
        ///  {0} {2} [&lt;file&gt; [...]]
        ///  {0} {3} &lt;directory&gt;
        ///  {0} {4} &lt;file&gt;
        ///  {0} {5} &lt;file&gt; ähnelt.
        /// </summary>
        internal static string Program_Usage {
            get {
                return ResourceManager.GetString("Program_Usage", resourceCulture);
            }
        }
    }
}
